Attempting to include table support

diff --git a/bin/repsep b/bin/repsep
--- a/bin/repsep
+++ b/bin/repsep
@@ -1,10 +1,33 @@
 #!/usr/bin/env bash
 
-if [[ $1 =~ ^(pdf||pgf|png)$ ]]; then
-        AS_MODULE="${2%.*}"
-        OUT="${AS_MODULE}.${1}"
-        python -c "mymod = __import__(\"$AS_MODULE\"); import matplotlib.pyplot as plt; plt.savefig(\"$OUT\")"
-else
-	echo "Invalid subcommand `$1`" >&2
-	exit 1
+IN_FILE=$(readlink -f $2)
+
+if [[ $2 =~ ^.*?\.csv$ ]]; then
+        if [[ $1 =~ ^pdf$ ]]; then
+                TEMP_DIR="/tmp/repsep/$(whoami)/$(date +'%Y%m%d%H%M%S')/"
+                mkdir -p "${TEMP_DIR}"
+                TEX_FILE="${TEMP_DIR}/outfile.tex"
+                OUT_FILE="${TEMP_DIR}/outfile.pdf"
+                echo $2
+                pushd ../repsep
+                        python -c "from convenience import repsep_create_table_tex; repsep_create_table_tex(\"${IN_FILE}\",\"${TEX_FILE}\")"
+                popd
+                pushd ${TEMP_DIR}
+                        pdflatex outfile.tex
+                popd
+                mv "${OUT_FILE}" .
+                rm -rf "${TEMP_DIR}"
+        else
+                echo "Invalid subcommand \`$1\` for input file \`$2\`" >&2
+                exit 1
+        fi
+elif [[ $2 =~ ^.*?\.py$ ]]; then
+        if [[ $1 =~ ^(pdf|pgf|png)$ ]]; then
+                AS_MODULE="${2%.*}"
+                OUT="${AS_MODULE}.${1}"
+                python -c "mymod = __import__(\"$AS_MODULE\"); import matplotlib.pyplot as plt; plt.savefig(\"$OUT\")"
+        else
+                echo "Invalid subcommand \`$1\` for input file \`$2\`" >&2
+                exit 1
+        fi
 fi
